elifesciences/elife-xpub

- server/schema/schema.graphqls
migrating https://gitlab.coko.foundation/xpub/xpub-elife/merge_requests/66/diffs.
> WIP: graphql schema for initial submission

- app/components/submission/FileUploads/FileUploadsPage.js
Funny how checking for the dropzone message in an e2e test would've caught this :)
> fix(ui): fix conversion.completed bug in file upload page

- docs/adr/0002-pubsweet.md
- docs/adr/0003-workflow.md
- docs/developing/PubSweet-Components.md
> Add and re-index ADR for PubSweet elifesciences/elife-xpub#161

- server/submission/resolvers.test.js
PubSweet server uses require-relative to load server components and this breaks jest mocking. Testing the resolvers directly circumvents the issue.
Benefits 
- jest mocks work as expected
- tests are shorter to write
- tests run a bit faster
Down sides 
- a little less realistic as all middleware is bypassed
- each test has to set up the context (currently just the user ID but may grow)
n/a
> test: refactor resolver tests to bypass apollo server

- docs/adr/0004-code-structure.md
A design record for the way to structure the server-side code.
> ADR for Code Structure

- app/components/submission/SubmissionPage.js
- app/components/submission/WithCurrentSubmission.js
- config/components.json
- config/default.js
- config/mailer.js
- server/db-helpers/index.js
- server/jest-setup.js
- server/submission/definitions.js
- server/submission/package.json
- server/submission/resolvers.js
- server/submission/resolvers.test.js
- yarn.lock
> feat(submission): create graphql mutation for form submission on final page

- package.json
Fixes cleaning ... tested locally...
```
npm run clean
yarn
```
> Fix the cleaning of node_modules to remove the one in server/submission

- app/app.js
- app/components/ui/molecules/FileUpload.test.js
- client/elife-theme/package.json
- package.json
- styleguide/components/Wrapper.js
- yarn.lock
> fix(elife-theme): use elifesciences org instead of pubsweet for theme

- app/components/ui/atoms/NotificationRibbon.js
- app/components/ui/atoms/NotificationRibbon.md
- app/components/ui/atoms/RibbonAction.js
re #228
This is only the Notification Ribbon atom from the referenced issue.
Locally on styleguide.
> feat(ui): add notification ribbon atom to ui

- app/components/dashboard/Dashboard.js
- app/components/submission/AuthorDetails/AuthorDetails.js
- app/components/submission/FileUploads/FileUploads.js
- app/components/submission/ManuscriptMetadata/ManuscriptMetadata.js
- app/components/submission/ReviewerSuggestions/FormSections.js
- app/components/submission/ReviewerSuggestions/ReviewerSuggestions.js
- app/components/ui/atoms/CalloutBox.js
- app/components/ui/atoms/CalloutBox.md
- app/components/ui/atoms/FormHeadings.js
- app/components/ui/atoms/FormHeadings.md
- app/components/ui/atoms/icons/Cross.js
- app/components/ui/atoms/icons/index.js
- client/elife-theme/src/elements/Heading.js
- client/elife-theme/src/elements/index.js
- client/elife-theme/src/index.js
- client/login-orcid/package.json
- package.json
- server/submission/package.json
- yarn.lock
**Includes pubsweet ui version bump**
Closes #226 and #229 
Apologies for the untidy merge commit situation. I did something strange and couldn't escape. (Well I found some 5-step instructions on how to do it...)
> feat: style Headings and CalloutBox

- app/components/submission/FileUploads/FileUploads.js
- app/components/submission/FileUploads/FileUploadsSchema.js
- app/components/ui/atoms/icons/TextBold.js
- app/components/ui/atoms/icons/TextItalic.js
- app/components/ui/atoms/icons/TextSub.js
- app/components/ui/atoms/icons/TextSup.js
- app/components/ui/atoms/icons/TextUnderline.js
- app/components/ui/atoms/icons/index.js
- client/elife-theme/src/elements/index.js
- client/elife-theme/src/elements/xpub-edit/index.js
- client/elife-theme/src/index.js
- server/submission/definitions.js
- Apply style overrides
- Add menu button icons
- Require minimum word count
Fixes #235 
Manually.
> feat: update cover letter editor

- app/components/submission/AutoSave.test.js
Add a test for the AutoSave component
Nope.
With Jest.
> test: AutoSave component

- app/components/submission/ManuscriptMetadata/ManuscriptMetadata.js
- client/elife-theme/src/elements/ui/Menu.js
- client/elife-theme/src/elements/ui/index.js
- client/elife-theme/src/index.js
- Fixes #223 
- Ready for review ~~but do not merge until [pubsweet!304](https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/304) is merged and published~~
Visually ~~when linked to PubSweet master.~~
> style: update Menu component

- app/components/submission/AuthorDetails/AuthorDetailsPage.js
- server/auth/fetchUserDetails.js
- server/submission/resolvers.js
- yarn.lock
Fix issues with the validation messages and the buttons being unresponsive.
#283 
Locally
> Fix the "prefill orcid details" from causing issues

- app/components/submission/ManuscriptMetadata/SubjectAreaDropdown.js
Remove the box shadow (hence the 90's feel)
#288 
Locally
> Remove box shadow from the MSA dropdown

- app/components/submission/SubmissionPage.js
- app/components/submission/WithCurrentSubmission.js
- app/components/submission/WizardStep.js
- app/components/ui/atoms/NotificationRibbon.js
- server/submission/definitions.js
- server/submission/resolvers.js
Fixes #285 
Fixes #262 
Manually, visually. End to end test coming in a separate PR as it requires some restructuring of the existing tests.
> feat: display notification ribbon for author verification

- client/elife-theme/src/elements/ui/Steps.js
Adds the tick to the progress indicator
#284 
Locally and with the PubSweet mod from https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/316/
> Add the tick to the background of the bullet for the progress indicator

- test/submission.e2e.js
I accidentally merged #307 with a work in progress commit which was testing the e2e test failures. This PR reverts that commit. 
I miss Gitlab's WIP feature 😢
> Revert "WIP debugging tests"

- client/elife-theme/package.json
Update elife-theme version to 1.0.1 (latest)
> feat(elife-theme): update elife-theme version to 1.0.1

- app/components/submission/FileUploads/FileUploads.js
- app/components/submission/ManuscriptMetadata/ManuscriptMetadata.js
- app/components/submission/ManuscriptMetadata/SubjectAreaDropdown.js
- app/components/submission/ReviewerSuggestions/FormSections.js
- app/components/submission/ReviewerSuggestions/ReviewerSuggestions.js
- app/components/submission/WizardStep.js
- app/components/ui/atoms/FormHeadings.js
- app/components/ui/atoms/Textarea.js
- app/components/ui/atoms/ValidatedField.js
- fix the internal spacing inside `ValidatedField` i.e. the distance between the component & the error message (was using the wrong variable name)
- add `Box` from `grid-styled` around each component on the wizard pages & apply `margin-bottom` to each one
relates #267 #203 #324
Visually, manually
> add vertical spacing to all form pages

- client/elife-theme/src/elements/ui/Checkbox.js
- client/elife-theme/src/elements/ui/Steps.js
Fixes #329 
Also fixes the ticks in the progress/steps component
> fix: URI encode SVG when used in data URI

- app/index.html
Prevents the mobile from shrinking the view port to fit
#362 
Locally using ngrok
> Add the meta tag to prevent mobiles shrinking to fit

- app/components/ui/atoms/Icon.md
- app/components/ui/atoms/icons/Upload.js
> feat(dropzone-molecule): start the upload progress at 12 o'clock

- server/submission/resolvers.js
Not fall over if Sciencebeam is not available
None
Not yet!
> Check the xmlData has an article before parsing

- docs/developing/ui-component-testing.md
Adds the procedure for ui component testing
> Add procedure for testing after chat with David

- app/components/pages/SubmissionWizard/WithCurrentSubmission.js
- app/components/pages/SubmissionWizard/formDataModifiers/CosubmissionModifier.js
- app/components/pages/SubmissionWizard/formDataModifiers/CosubmissionModifier.test.js
- test/submission.e2e.js
While working on adding the people picker to the form, I started creating a new data modifier which led me to do a bit of refactoring.
- Fix bug where the cosubmission could not be removed
- Rename some variables and functions to avoid ambiguity
- Add test for modifier
Manually and with Jest.
> fix: cosubmission form data modifier

- app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerModal.js
- app/components/ui/molecules/SearchBox.js
> 439 integrate search box

- app/components/pages/SubmissionWizard/steps/Editors/EditorsContent.js
- app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerControl.js
- app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerModal.js
- app/components/ui/atoms/FormHeadings.js
> feat(PeoplePicker): add title to People Picker

- server/xpub/entities/manuscript/index.js
> fix: deleting manuscript from dashboard

- server/xpub/entities/manuscript/index.js
> feat: set 'corresponding' flag on author

- app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerModal.js
- app/components/ui/molecules/PeoplePicker.js
- app/components/ui/molecules/SearchBox.js
> feat(PeoplePicker): improve people picker filtering functionality

- app/components/pages/SubmissionWizard/steps/Editors/EditorsContent.js
- app/components/ui/molecules/SearchBox.js
- client/texture/TextureEditor.js
- config/custom-environment-variables.js
Fixing the linting errors appearing in https://gitlab.com/elifesciences/elife-xpub/-/jobs/90509269
#368   
Running `yarn lint` locally
> Fixing lint errors and tests in develop

- package.json
- yarn.lock
- Fixes layout bug, introduced by dependency updates
fixes #500 
visually
> fix: prevent v3 of styled-system from breaking grid-styled layout

- app/components/pages/SubmissionWizard/steps/Editors/EditorsContent.js
- app/components/pages/SubmissionWizard/steps/Editors/FormSections.js
- app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerControl.js
- app/components/pages/SubmissionWizard/steps/Submission/index.js
- app/components/pages/SubmissionWizard/steps/Submission/schema.js
- app/components/ui/molecules/FileUpload.js
- app/components/ui/molecules/FileUpload.test.js
- Small changes to the copy, based on the proofreading work done by eLife's Press Officer
- Add a number next to each field in the suggested reviewers section, so that "name" and "email" fields are clearly connected, even on mobile view
fixes #508 #459
N/A
> update copy based on the proofread from eLife's Press Officer & designs for reviewer suggestions section

- app/components/pages/SubmissionWizard/steps/Submission/index.js
Adds the remaining eLife article type options to the dropdown menu.
> Add additional article types

- package.json
- yarn.lock
re #544
The new version has this change https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/390
> feat(dependencies): update pubsweet-client to latest version

- app/components/ui/molecules/FileUpload.js
> revert(dropzone-molecule): remove upload progress from dropzone molecule

- app/components/ui/molecules/PeoplePicker.js
this was left here by accident
> fix(SearchBox): remove matchIndex from multi words match

- server/meca/disclosure.js
- server/meca/disclosure.test.js
- server/meca/package.json
- yarn.lock
Closes #561 
[An example PDF that it generates](https://github.com/elifesciences/elife-xpub/files/2360746/7de61e41-b163-4108-9198-1492e2b54a1f.pdf)
Very basic unit test. Could improve on this using another package to parse the PDF and assert on its contents.
> feat: function to generate disclosure agreement PDF

- server/meca/article.helpers.js
- server/meca/article.js
- server/meca/article.test.data.json
- server/meca/article.test.js
- server/meca/package.json
- test/http-mocks/success/api.elifesciences.org-443/153633381273344998
- test/http-mocks/success/api.elifesciences.org-443/153633381273943620
- yarn.lock
Closes #562 although there are some outstanding questions on that issue and a little more work will be required once the eLife people API is updated.
Unit tests.
> feat: function to generate MECA article XML

- app/components/ui/molecules/PeoplePicker.test.js
integration with people picker modal
re #527
> test(PeoplePicker): write integration tests for search box

- app/components/ui/molecules/SearchBox.test.js
- client/elife-theme/src/icons/material/Search.js
> test(SearchBox): add tests for SearchBox component

- config/default.js
- config/test.js
- server/meca/index.js
- server/meca/index.test.js
- server/xpub/entities/manuscript/resolvers.js
- server/xpub/entities/manuscript/resolvers.test.js
- test/submission.e2e.js
Closes #566 
Also closes #533 
Jest test of resolver plus check that a file was uploaded to the mock SFTP server in the E2E happy path flow.
> feat: connect MECA export to submission form

- app/components/ui/molecules/PeoplePicker.test.js
- app/components/ui/molecules/SearchBox.test.js
- client/elife-theme/src/icons/material/Cross.js
> test(SearchBox): add icon tests

- test/pageObjects/submission.js
Cuts test run time from ~1m30 to ~1m
> test: fix e2e checkbox selectors to avoid waits

- app/components/pages/SubmissionWizard/steps/Files/index.js
- app/components/ui/molecules/FileUpload.js
- app/components/ui/molecules/FileUpload.md
- app/components/ui/molecules/FileUpload.test.js
Closes #513
Closes #597 
Addresses client side portion of #595
> Update file upload design and error messaging

- server/xpub/entities/manuscript/resolvers.js
- server/xpub/entities/manuscript/resolvers.test.js
- yarn.lock
Closes #605 and also:
- Fix race condition by pausing stream until all listeners are added.
- Gracefully handle ScienceBeam failure.
> fix: upload manuscript resolver error handling

- server/xpub/entities/manuscript/resolvers.js
Follow up to #607 in light of the fact that [you shouldn't mix](https://nodejs.org/api/stream.html#stream_choose_one_api_style) `.pipe()` and `.on('data')`. Instead this uses a transform stream to handle the upload progress reporting and then passes the data on untouched for use in the file save stream.
> fix: improve stream handling in upload resolver

- app/components/ui/molecules/FileUpload.js
- config/default.js
- server/xpub/entities/manuscript/resolvers.js
- server/xpub/entities/manuscript/resolvers.test.js
re #595
This is the second task from #595
> feat(server): add file size check in uploadManuscript resolver

- server/xpub/entities/manuscript/resolvers.js
wait for at least 500ms before sending upload progress
just a shot in the dark
re #546
> feat(graphql-subscriptions): wait for at least 500ms

- app/components/ui/molecules/FileUpload.js
- app/components/ui/molecules/FileUpload.test.js
> revert(FileUpload): show manuscript upload progress again

- config/ci.js
- config/demo.js
- config/logger.js
- config/prod.js
- server/meca/upload/index.js
- server/xpub/entities/manuscript/resolvers.js
- server/xpub/entities/user/helpers/elife-api.js
- server/xpub/entities/util.js
- Log JSON to file in `prod` and `demo`.
- Enrich some logs with objects and IDs to make searching easier.
Closes #618 
Log output inspected locally.
> feat: configure logging

- config/mailer.js
> feat(mailer): configure nodemailer with the right smtp server

- docs/developing/README.md
Updated docs to follow current development practices when it comes to running the app locally.
#677
> docs: updated local development docs

- config/development.js
- docker-compose.yml
- package.json
At @giorgiosironi 's suggestion - added fake s3 container to docker compose.
See https://github.com/elifesciences/elife-xpub/pull/707#discussion_r222366693
> Add the fake s3 container to docker compose

- server/xpub/entities/manuscript/resolvers.js
> fix(uploadManuscript): only log error message on science beam failure

- styleguide.config.js
> fix(styleguide): use the same resolver from webpack in styleguide

- config/default.js
- server/xpub/entities/manuscript/resolvers.js
> feat(uploadManuscript): add timeout for science beam conversion

- config/custom-environment-variables.js
- config/staging.js
Adds environment variables for the deployment - going to be used by the repos formula and deployment
> Add some custom vars for MECA SFTP

- config/staging.js
Switch to use Journal staging server to log in to xPub.
> config: turn off mock login

- client/elife-theme/src/global.js
> fix(fonts): fix bad font path

- app/components/ui/molecules/PeoplePicker.js
- app/components/ui/molecules/PeoplePicker.test.js
> feat(SearchBox): search for matches anywhere in the person pod

- app/components/ui/molecules/SearchBox.js
- app/components/ui/molecules/SearchBox.test.js
> feat(SearchBox): temporarily hide list of suggestions

- app/components/global/layout/Centerer.js
- app/components/pages/SubmissionWizard/WizardStep.js
- app/components/pages/SubmissionWizard/steps/Submission/index.js
> fix: flexbox text-overflow issue

- app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerModal.md
`PeoplePickerModal.md` is outdated. The Search Box functionality has changed and should be reflected in the docs.
> docs(PeoplePicker): update PeoplePickerModal.md with new search functionality

- app/components/ui/molecules/Tabs.js
- app/components/ui/molecules/Tabs.md
- package.json
- yarn.lock
Closes #775 
Currently looks like:
Visually in styleguidist.
> feat: tabs component using react-tabs

- app/components/pages/ThankYou/ThankYou.js
- app/components/pages/ThankYou/ThankYou.md
- app/components/pages/ThankYou/index.js
- app/routes.js
Thank You page required after completing wizard form with button returning user to dashboard and text requesting they bookmark dashboard page.
Adds a new route of /thankyou/:id to the app and a component for displaying the required information.
#736 
Locally
> Create a 'Thank You' page to finish submission

- app/components/pages/SubmissionWizard/WizardStep.js
- app/components/pages/SubmissionWizard/WizardSubmit.js
- app/components/pages/SubmissionWizard/index.js
- app/components/pages/SubmissionWizard/steps/Disclosure/index.js
- app/components/pages/SubmissionWizard/steps/Editors/EditorsPage.js
- app/components/pages/SubmissionWizard/steps/Editors/EditorsPage.md
- app/components/pages/SubmissionWizard/steps/Editors/EditorsPage.test.js
- app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerControl.js
- app/components/ui/molecules/ModalDialog.js
- app/components/ui/molecules/ModalDialog.md
- app/components/ui/molecules/ModalHistoryState.js
- app/components/ui/molecules/ModalHistoryState.test.js
- client/elife-theme/src/elements/ui/Button.js
- config/default.js
- server/meca/export.js
- server/xpub/test/mock-s3-server.js
- test/pageObjects/wizardStep.js
- test/submission.e2e.js
- yarn.lock
Apologies for the big PR. One this led to another and here we are. Happy to break it into smaller pieces but they will need to be fed in sequentially as it's all a bit interlinked.
- Add confirmation dialog at end of the wizard, closes #511 
- Create a dummy submit button on final step of wizard
- Move real submit button into a ModalDialog
- Add size prop to ModalDialog as it is not obvious how to size automatically based on the content
- Create helper component to save modal state in browser history
- Update Editors step to use this component
- Update Button min-width width from new style guide
- Fix bug where auto save on final step of wizard caused a submission
- Re-enable flaky SFTP content end to end test with more logging
- ~~Add check to prevent updating a submitted manuscript~~ …
> Wizard final step confirmation modal

- app/components/global/AppBar/ProfileMenu.js
- app/components/global/AppBar/ProfileMenu.md
- app/components/global/AppBar/ProfileMenu.test.js
- app/components/ui/atoms/PopOverPanel.js
- app/components/ui/atoms/PopOverPanel.md
- client/elife-theme/src/icons/material/Profile.js
- client/elife-theme/src/index.js
> feat: app bar profile menu component

- app/index-production.html
Adds missing changes to production html that were added in #809 
Locally
> Staging fix

- config/default.js
- config/end2end.js
- config/prod.js
- config/staging.js
Configures the correct buckets for all of our environments.
- Default: `dev-elife-xpub`
- Production: `prod-elife-xpub`
- Staging: `staging-elife-xpub`
- End-to-end: `end2end-elife-xpub`
- Development: fake S3
Closes #826
> Bucket config for staging, end2end and production

- .gitignore
- styleguide.config.js
- styleguide/config.json
Change in client side config broke style guide loading.
> fix: load styleguide config from static JSON file

- app/components/ui/atoms/CalloutTextBox.js
- app/components/ui/atoms/CalloutTextBox.md
> feat: callout text box

- config/development.js
- docs/developing/quick-start.md
- server/meca/__snapshots__/export.test.js.snap
- server/meca/file-generators/__snapshots__/article.test.js.snap
- server/meca/file-generators/article.js
Closes #846
Tested locally with a connection to the dev S3 Bucket in AWS
> Export to MECA the opposed reasons

- app/components/global/layout/SectionalLayout.js
- app/components/global/layout/SectionalLayout.md
> feat: sectional layout component

- app/components/ui/molecules/RefTable.js
- app/components/ui/molecules/RefTable.md
Closes #815 
Manually in styleguide.
> feat: ref table component with footer

- app/components/ui/molecules/StaffCard.js
- app/components/ui/molecules/StaffGrid.js
- app/components/ui/molecules/StaffGrid.md
> StaffGrid: generic Grid to display staff cards

- app/components/pages/AuthorGuide/EditorialProcess.js
- app/components/pages/AuthorGuide/Full.js
- app/components/pages/AuthorGuide/JournalPolicies.js
- app/components/pages/AuthorGuide/Types.js
- app/components/pages/Staff/EditorialPage.js
- app/components/ui/molecules/StaffGrid.md
Hosts the files that were in eJP on S3
Also fix staff photos by getting them from the Journal site
Closes #872 
Locally with the styleguide
> Add guides to s3. Also get all images from the journal site

- app/components/global/AppBar/AppBar.js
- app/components/ui/molecules/BurgerMenu.js
> style(AppBar): create responsive layaout for mobile view

- app/components/ui/molecules/BurgerMenu.js
Feedback on previous #876 
Add functionality to click out of mobile menu to close it.
add onClick to NavList items to close menu on click
closes #880
> 880 - BurgerMenu follow up tasks

- app/components/pages/Dashboard/index.js
> style(Dashboard): fix text in the bottom of the dashboard

- scripts/gitlab-mirror/Dockerfile
- scripts/gitlab-mirror/examples/docker.sh
- scripts/gitlab-mirror/mirror
Improves the mirroring process by triggering gitlab's mirror job every 60 seconds.
> Pipeline mirroring job improvements

- docs/developing/README.md
- docs/developing/screencasts.md
> Add the screencasts

- app/components/pages/Dashboard/index.js
> fix(SubmissionButton): button does not work in mobile

- app/components/ui/molecules/DashboardListItem.js
update breakpoint for mobile view
closes: #923 
go to style guide and require a mobile view
> fix(DashboardListItem): update breakpoint for mobile view

- app/components/pages/StaticPages/ContactUs/EditorialStaff.js
- app/components/pages/StaticPages/ContactUs/ProductionStaff.js
- app/components/ui/molecules/StaffGrid.js
modify responsive to one column on mobile view, and changed pictures to have the same aspect ratio.
closes: #921
> refactor(StaffPages): modify responsive to one column on mobile view

- app/components/ui/atoms/ManuscriptStatus.js
- app/components/ui/atoms/ManuscriptStatus.md
- app/components/ui/molecules/DashboardList.md
- app/components/ui/molecules/DashboardListItem.md
- server/xpub-server/entities/manuscript/resolvers.js
spelling issue in the dashboard items
closes: #933 933
> fix(Dashboard): fix spelling issue

- app/components/pages/Dashboard/index.js
####What does this PR do?
fix space between footer and empty message
closes: #908
> fix(Dashboard): fix space between footer and empty message

- app/components/ui/molecules/DashboardListItem.js
make title grey for submitted documents
closes: #919
> style(DashboarListItem): make title grey for submitted documents

- server/xpub-server/routes.js
- server/xpub-server/routes.test.js
refactor ping to just list the bucket in S3, and some refactoring around the error handling
closes: #950
> refactor(ping): refactor ping enpoint

- .gitignore
- .gitlab-ci.yml
- config/custom-environment-variables.js
- config/default.js
- config/styleguide.js
- package.json
- scripts/upload-to-s3.js
- webpack/webpack.production.config.js
Deploys the styleguide to S3 for each PR and develop.
Closes #408
> Styleguide deployment

- Dockerfile
- Dockerfile-development
- config/default.js
- config/non-serializable/fake-mailer.js
- config/prod.js
- docs/developing/README.md
- docs/developing/email.md
- package.json
- server/xpub-model/entities/manuscript/index.js
- server/xpub-server/entities/manuscript/resolvers.js
- server/xpub-server/entities/manuscript/resolvers.test.js
- templates/dashboard-email-html.pug
- templates/dashboard-email-text.pug
- yarn.lock
Sends a dashboard email to the author when their email changes.
Closes #858 
Locally
> Email user with a link to the dashboard

- app/components/pages/Login/index.js
there is an issue in login page for mobile, that overlaps the header
closes: #926
> fix(Login): fix issue overlapping header

- app/components/pages/StaticPages/AuthorGuide/EditorialProcess.js
- app/components/pages/StaticPages/ScrollToTop.js
- app/components/pages/StaticPages/index.js
not scrolling to the top when clicking on the relative link `read more`
closes: #956
> Static Pages: not scrolling to the top when click on relative link

- app/components/pages/SubmissionWizard/steps/Files/index.js
> fix: don't crash the page if the upload subscription errors

- docs/deploying/README.md
- docs/deploying/infrastructure.md
- docs/deploying/k8s.md
- docs/deploying/pipeline.md
Needed to update the docs with new k8s knowledge.
> Update the documentation with k8s

- app/components/pages/StaticPages/ContactUs/ContactELife.js
emails incorrect displayed
closes #878
> change email links

- server/xpub-model/entities/manuscript/index.js
- server/xpub-model/entities/manuscript/index.test.js
Closes #1014 
I'm unable to test this outside of Staging as our login mock only supports a single user.
> Fix manuscripts on dashboard

- server/xpub-model/entities/user/helpers/elife-api.js
- server/xpub-server/entities/user/resolvers.test.js
Combines `expertises` and `focuses` as subjectAreas for senior and reviewing editors
fixes #627
Jest
> Adding the focuses to subjectAreas

- config/end2end.js
There are some debug-level calls about the people picker that could help, well, debug it.
> Set log level to `debug` in end2end

- server/xpub-server/health.js
- server/xpub-server/index.js
- server/xpub-server/routes.js
- server/xpub-server/routes.test.js
Remove necessary logging
Closes #1069 
Locally ... healthy - missing db - healthy
> Use our own db check instead of one from pubsweet

- styleguide/config.json
Fixes config in styleguide
Closes #1093 
Checked styleguide locally - no tests for styleguide
> Change the config for styleguide to reflect recent changes

- app/components/pages/Dashboard/operations.js
- app/components/pages/SubmissionWizard/SavePageStatus.js
- app/components/pages/SubmissionWizard/SubmissionOperations.js
- app/components/pages/SubmissionWizard/operations.js
- app/components/ui/molecules/DashboardListItem.js
- server/meca/export.test.data.json
- server/meca/file-generators/article.test.data.json
- server/xpub-model/entities/manuscript/index.js
- server/xpub-model/migrations/1542896967-alter-manuscript.sql
- server/xpub-server/entities/manuscript/resolvers/index.js
- server/xpub-server/entities/manuscript/resolvers/index.test.data.js
- server/xpub-server/schema/xpub.graphqls
refactor field name in the manuscript model and in the database
changes:
formState to LastStepVisited
closes 1097
> refactor formStatus field name, to provide a more descriptive name

- app/components/pages/SubmissionWizard/steps/Submission/SubjectAreaDropdown.test.js
- config/default.js
Updates the subject areas to match most recent Journal changes.
Closes #1038 
@hdrury1 modified tests.
@diversemix tested locally.
No UI changes
> Update subject areas

- app/components/ui/molecules/DashboardListItem.js
- test/lastStepVisited.browser.js
- test/pageObjects/dashboard.js
browser test for complete the issue #1063
test in the browser the behaviour defined on #1063
- [x ] Browser tests
> browser test for last visited page

- app/components/ui/molecules/SearchBox.js
Adds relevant placeholder text to People Picker search box
Closes #1075 
Please indicate the need for this change to be tested. If not please justify, if so then at what levels. **Reviewers** ensure that these test requirements are also reviewed.
Tests failing on my machine but passing on Peter's.
> Update people picker search placeholder

- package.json
- yarn.lock
Fix vulnerability in `event-stream`
Closes #1120 
Test in CI is sufficient as change is a third party dependency
> Bump version to testcafe-browser-provider-browserstack@1.5.1

- server/meca/file-generators/article.test.js
- server/xpub-server/entities/manuscript/resolvers/scienceBeamApi.js
- server/xpub-server/entities/manuscript/resolvers/uploadManuscript.js
- server/xpub-server/entities/manuscript/resolvers/uploadManuscript.test.js
- server/xpub-server/entities/user/resolvers.test.js
As stated 
Closes #1111
This is all about tests - so tested locally
> Fix tests failing when REPLAY=record

- .gitlab-ci.yml
For https://github.com/elifesciences/elife-xpub/issues/1100 in favor of Jenkins new support for them
> Remove Gitlab CI review environments

- app/components/pages/SubmissionWizard/steps/Editors/EditorsPage.js
- app/components/ui/PeoplePicker/PeoplePickerControl.js
- app/components/ui/PeoplePicker/PeoplePickerLayout.js
- app/components/ui/PeoplePicker/PeoplePickerLayout.md
- app/components/ui/PeoplePicker/PeoplePickerLogic.js
- app/components/ui/PeoplePicker/PersonInfoModal.js
- app/components/ui/PeoplePicker/PersonPod.js
- app/components/ui/PeoplePicker/PersonPod.md
- app/components/ui/PeoplePicker/PersonPodGrid.js
- app/components/ui/PeoplePicker/SearchBox.js
- app/components/ui/PeoplePicker/SearchBox.md
- app/components/ui/PeoplePicker/types.js
- server/xpub-model/entities/user/helpers/elife-api.js
PR https://github.com/elifesciences/elife-xpub/pull/1132 + a few fixes for the console errors
Also fixes #1141
> People picker refactor (2)

- app/components/pages/SubmissionWizard/steps/Files/ManuscriptUpload.js
Changes the dropzone border to match designs
Closes #1067 
Please indicate the need for this change to be tested. If not please justify, if so then at what levels. **Reviewers** ensure that these test requirements are also reviewed.
> Make dropzone border solid

- app/components/pages/SubmissionWizard/WizardSubmit.js
Fixes the typo in the final modal after completing the wizard.
Please indicate the need for this change to be tested. If not please justify, if so then at what levels. **Reviewers** ensure that these test requirements are also reviewed.
> Fix typo in submit modal

- config/custom-environment-variables.js
- config/non-serializable/mailer.js
Tried a number of ways but this is the least friction (take a look at #998)  - probably want a pubsweet change at some point.... I dunno.
Closes #998 
This is only part of the configuration setup - this needs to be tested in the pipelines
> Allow email to be configured with env vars 

- Jenkinsfile
At https://s3.amazonaws.com/ci-elife-xpub-styleguide/develop/index.html (won't be done by this PR's build, as it's not merged yet)
> Deploy styleguide of develop branch

- app/components/ui/PeoplePicker/PeoplePickerBody.js
- app/components/ui/atoms/SelectedItem.js
allow selection of users to grow in lines, not in the text
closes #1129
> fix issue to display multiple text lines on selected people

- app/components/ui/molecules/DashboardList.js
adds an extra space between titles on an empty dashboard
closes #1138
> add space between titles on an empty dashboard

- app/components/pages/SubmissionWizard/steps/Files/SupportingUpload.js
just display the message when reaching the limit 
closes #1160
> avoid display warning message of maximum files till reach the limit

- Dockerfile
- Dockerfile-development
- docs/deploying/README.md
- docs/deploying/dockercatalogue.md
Allows specifying a pinned version of the xpub base image
None - this was an Andon moment
Will be tested in the pipeline
> Use a pinned version of the xpub docker image

- config/non-serializable/mailer.js
- docs/developing/architecture.md
Allows authentication to SMTP server
Closes #1192
Visually inspected - Not tested
> Add configurable auth to mailer.js

- server/xpub-server/entities/manuscript/resolvers/updateManuscript.js
To aid testing of https://github.com/elifesciences/elife-xpub/issues/890
> Add positive log on confirmation email

- package.json
Improve the clean command
non
Locally - just a developer change
> Improve clean to find all node_modules

- .gitignore
- package.json
- server/meca/package.json
- server/xpub-model/entities/manuscript/index.js
- server/xpub-model/entities/manuscript/index.test.js
- server/xpub-model/package.json
- server/xpub-server/entities/manuscript/resolvers/uploadManuscript.js
- yarn.lock
- Add refresh() to manuscript to prevent saving stale data
- Adds data integrity checks to manuscript.save()
Closes #1162 
Added unit tests for saving - no added browser test or end2end tests as this code will be exercised with the existing tests.
> Fix autosave with manuscript refresh

- Jenkinsfile
Disables browser tests as they are intermittently failing and we don't know why.
Closes #1228
Please indicate the need for this change to be tested. If not please justify, if so then at what levels. **Reviewers** ensure that these test requirements are also reviewed.
> Disabled browser tests

- PULL_REQUEST_TEMPLATE.md
> Update template now we have removed browser tests from the pipeline.

- test/http-mocks/success/static.hotjar.com/154653040377623453
Adds a missing file for the hotjar request
None
> Add the replay file for hotjar to see if it fixes hanging

- scripts/USER-TOOL.md
- scripts/user-tool.js
- test/http-mocks/success/static.hotjar.com/154653040377623453
Add a tool to help diagnose ORCiD / xPub / Profiles Service issues
Closes #1031
As this only a tool - all testing has been done on the developer box. This will not be used in Production
> Add user-tool

- app/components/pages/SubmissionWizard/steps/Submission/index.js
Updates labels of co-sumission boxes in wizard
Closes #1026 
Please indicate the need for this change to be tested. If not please justify, if so then at what levels.
> Update co-submission labels

- server/meca/__snapshots__/export.test.js.snap
- server/meca/file-generators/coverLetter.html
- server/meca/file-generators/coverLetter.test.js
Removes the appendix from the cover letter.
Closes #1261
Tested locally, including browser tests
> Remove appendix from cover letter and update tests

- server/meca/Readme.md
- server/meca/__snapshots__/export.test.js.snap
- server/meca/export.js
- server/meca/export.test.data.json
- server/meca/export.test.js
- server/meca/file-generators/archive.js
- server/meca/file-generators/archive.test.js
- server/meca/file-generators/manifest.test.js
- server/xpub-server/entities/manuscript/resolvers/removeSupportingFiles.test.js
- server/xpub-server/entities/manuscript/resolvers/submitManuscript.js
- server/xpub-server/entities/manuscript/resolvers/submitManuscript.test.js
Adds the supporting files to the zip package.
Step 2 of #1164
Please indicate the need for this change to be tested. If not please justify, if so then at what levels. 
- Unit / Integration tests - changed
- Browser tests not neccessary
- E2E tests out of scope
> Add Supporting files to Zip
