elifesciences/elife-xpub

README.md

This does not render on github but should do so in a markdown preview in Atom or similar.

Add documentation on how the CI/CD works

---

.gitlab-ci.yml

will hopefully fix:
```
error during connect: Get http://docker:2375/v1.37/version: dial tcp: lookup docker on 100.64.0.10:53: no such host
```

fix(ci): update docker host for kubernetes

---

.gitlab-ci.yml

ugh: https://gitlab.com/gitlab-org/gitlab-runner/issues/2229
will hopefully fix:
```
Submission › createSubmission › adds new manuscript to the db for current user with stage INITIAL
getaddrinfo ENOTFOUND postgres postgres:5432
```

fix(ci): change PG_HOST for k8s

---

package.json
yarn.lock

Second page of submission was giving a warning like this
```
Warning: Failed prop type: Invalid prop `accept` of type `array` supplied to `Dropzone`, expected `string`.
```
The `accept` prop from react-dropzone doesn't accept an array of strings, but apparently it works with a string of comma separated values: https://github.com/react-dropzone/react-dropzone/pull/142
Reloaded page 2 of submission, no more warnings. Also, I uploaded a docx, pdf and png files and it accepted the first 2 but not the last one.

fix(dropzone-molecule): fix react-dropzone warning about accepted files

---

app/components/submission/ReviewerSuggestions/ReviewerSuggestionsSchema.js
app/components/submission/SubmissionPage.js
app/components/submission/WithCurrentSubmission.js

Moving from individual form instances to a single form instance for the whole submission form had the side effect of persisting field "touched" status across steps in the wizard. This manifested itself as a bug which caused validation errors for all fields to be displayed as soon as any field was blurred. 
See #188 
Locally, manually.

fix: use key to force remount of formik component on each page

---

package.json

Jest previously had a bug relating to coverage reporting when using the projects feature. This appears to have been resolved.
This enables coverage reporting in Jest. The config in Gitlab CI has been update to parse the reported coverage figure. It remains to be seen how to get this displayed on the GitHub PR. 
This PR is the test.

ci: enable test coverage reporting

---

client/elife-theme/src/index.js

- use `boxShadow` as theme variable name instead of `dropShadow`
Fixes #237
Relates https://gitlab.coko.foundation/pubsweet/design/issues/29

fix(elife-theme): use 'boxShadow' instead of 'dropShadow'

---

app/app.js
client/elife-theme/src/index.js

- replace them variables `verticalXxs`...`verticalXxl` with `space`
- remove `theme.space` from `app.js`, since it now already exists in the theme
Fixes #236

Replace vertical grid units with space

---

config/test.js
docs/testing/README.md

The end-to-end tests previously connected to the default database. They are configured to clear the database before running the tests which resulted in the main Postgres database being deleted on each test run. This is potentially very bad.
Manually, locally.

fix: don't wipe the main database when running the end-to-end tests

---

app/components/submission/ManuscriptMetadata/SubjectAreaDropdown.test.js

- simplest possible unit test - checking whether a few elements appear on the page when shallow rendered
- integration tests (SubjectAreaDropdown + component from react-select library)
Fixes #195 
Validation messages - responsibility of `ValidatedField` component & overall page component
Struggling with `react-select` + enzyme. Cannot simulate click behaviour, which makes it difficult to test the following:
- When 2 options are selected -> disables the dropdown
- Given that 2 options are selected, when 1 option is deleted, then the dropdown is re-enabled

195 subject area dropdown tests

---

test/submission.e2e.js

Previously this end-to-end test tried to click on a background element. This causes a delay while TestCafe waits for the element to become visible (see https://github.com/DevExpress/testcafe/issues/2381).
Switching to a different selector shaves ~10 seconds off the test run time.
n/a

test: update selector to avoid max wait

---

app/components/ui/atoms/icons/Checkmark.js
client/elife-theme/src/elements/ui/Checkbox.js
client/elife-theme/src/elements/ui/index.js
client/elife-theme/src/index.js

- Fixes #221 
- Add Checkmark icon component but use inline data uri until icons are supported in themes
- Reorganise theme override folder structure to reflect object structure
- Ready for review ~~but waiting on [pubsweet!301](https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/301)~~
Visually ~~when linked to the latest `@pubsweet/ui`~~.

style: update Checkbox component

---

app/components/submission/ManuscriptMetadata/SubjectAreaDropdown.js
app/components/ui/atoms/icons/TagRemovalIcon.js
client/elife-theme/src/index.js

Note: to style `react-select`'s sub-components, we need to use a custom styles object - see [the docs](https://deploy-preview-2289--react-select.netlify.com/styles#style-object). This looks similar to styled components, but in fact uses "emotion".
This is the component structure for the multi-select version of `react-select`:
- First diagram - shows when there is only a placeholder present & the ability to type a letter in the input.
- Second diagram - shows how the structure of the ValueContainer changes after a user selects their option(s)
1. Tidy up:
- fix typo in eLife theme - "col**our**Warning" -> `colorWarning`
- remove bottom margin from overall component - relates #238 
2. Then update SubjectAreaDropdown component to conform to styleguide - see issue #225:
_Border colour_
- alter …

style(SubjectAreaDropdown): sub components of react-select to conform to new elife theme

---

app/components/submission/ReviewerSuggestions/ReviewerSuggestions.js

pubsweet has removed their `PlainButton` atom & now has a `Action` component, which we need to use instead
Replaces buttons with links on page 4
fixes #271

fix: change PlainButton to Action - after breaking change in pubsweet

---

app/components/submission/ManuscriptMetadata/ManuscriptMetadata.js
app/components/submission/ReviewerSuggestions/ReviewerSuggestions.js

Designs have changed the order of the Back & Next buttons.
Page 1 doesn't have a Back button
Page 2 has already been updated at some point.
- Switch Back & Next on page 3
- Switch Back & Submit on page 4
#269

fix: re-order Back and Next/Submit buttons on pages 3 & 4

---

app/components/submission/FileUploads/FileUploadsSchema.js

Validation was miscounting words which meant the cover letter was valid by default.
Also the validation message was too vague and causing confusion when people typed gibberish into the input instead of separate words.
Manually.

fix: cover letter editor validation

---

app/components/dashboard/Dashboard.js
app/components/dashboard/DashboardPage.js
server/db-helpers/index.js
server/submission/definitions.js
server/submission/resolvers.js

I've taken the initiative and added some more functionality to the dashboard view. I frequently have to manipulate the database to delete an in progress manuscript. This is easy enough on a development machine but it's a bit trickier on staging/demo. This is very much a temporary solution but will hopefully be useful until we have a better idea of the design and functionality of the dashboard.
FWIW on previous projects I've found it useful to create a special admin dashboard with this kind of functionality and some built in checks to ensure it can't get deployed to production. 
Manually.

feat: temporary dashboard view

---

app/components/submission/AutoSave.js
app/components/submission/AutoSave.test.js
app/components/submission/FileUploads/FileUploads.js
app/components/submission/FileUploads/FileUploadsPage.js
app/components/ui/molecules/FileUpload.js
config/test.js
test/submission.e2e.js

- Pass the Texture preview page URL down to the file upload component
- Add a test into the submission flow end to end test
- Fix DAR server config in `test` environment
- Make the `AutoSave` component trigger a save when it gets unmounted. This should ensure that the latest data is saved when a user navigates away from the form. Note this is only for "in-app" navigation, it doesn't account for full page reloads like navigating to a different site.
Related to #234.
TestCafe.

fix: correct preview link on manuscript upload component

---

app/components/dashboard/Dashboard.js
app/components/dashboard/DashboardPage.js
app/components/submission/WithCurrentSubmission.js
test/pageObjects/dashboard.js
test/pageObjects/file-uploads.js
test/pageObjects/index.js
test/submission.e2e.js

- Add a test to assert that the manuscript goes into the QA stage after initial submission
- Refetch the dashboard query on submit so that the data on the dashboard is up to date. It's not yet clear what the best approach is for this.
- Create a page object for the file uploads page test
- Add a wait in the saving test which was sometimes failing because it reloaded the page before the save had completed
With TestCafe.

test: add end-to-end test assertions for manuscript stage transition

---

package.json
yarn.lock

They've fixed various bugs since we last upgraded it. Hopefully this might help with some of the issues we're having. 🤞

chore: upgrade testcafe dependency to latest

---

test/submission.e2e.js

Failing tests fixed by a simple wait
None
Locally

fix: e2e tests - add a wait for a second before looking for the element

---

.gitlab-ci.yml
app/components/submission/WizardStep.js
test/pageObjects/dashboard.js
test/pageObjects/file-uploads.js
test/pageObjects/index.js
test/pageObjects/metadata.js
test/pageObjects/submission.js
test/pageObjects/suggestions.js
test/submission.e2e.js

The "Happy path" test was getting too complex and jeopardising its happiness.
This simplifies the happy path and moves diversions and special cases into other tests. One of these includes a test for the notification ribbon being displayed.
Also create page objects for every page to improve maintainability of the tests.

test: split submission flow into two tests

---

app/components/submission/AuthorDetails/AuthorDetails.js
app/components/submission/AutoSave.js
app/components/submission/FileUploads/FileUploads.js
app/components/submission/ManuscriptMetadata/ManuscriptMetadata.js
app/components/submission/ReviewerSuggestions/ReviewerSuggestions.js
app/components/submission/SubmissionPage.js
app/components/submission/WizardStep.js
test/submission.e2e.js

Instead of having the buttons on each page, move them up into the shared `WizardStep` component. As well as reducing duplication, this paves the way for the QC page which needs to combine the four steps into a single form with a single submit button.
No, going off road a little here to distract myself from the misery of debugging end to end tests.
Visually.

style: apply consistent spacing to next and previous buttons

---

app/components/submission/WizardStep.js
server/submission/resolvers.js
server/submission/resolvers.test.js
test/pageObjects/submission.js
test/submission.e2e.js

Product requirements now have the corresponding author emailed on Submit, rather than on clicking Next in step 1 of the wizard.
The corresponding author no longer needs to be added to the manuscript object in the middle of the submission process (`updateSubmission` resolver). Differentiating between the submitter email address & the corresponding author email address is to be completed in another ticket - issue #309 
- Removes code that adds corresponding author to the manuscript object on clicking 'Next' & associated tests
- Moves the sending of an email from the 'updateSubmission' resolver to the `finishSubmission` resolver  
**Note: This email is currently sent every time a user clicks 'Submit'. In order to check whether it should be sent, we first need to store the submitter's email …

Email corresponding author on Submit instead of Next

---

app/components/ui/atoms/Textarea.js
client/elife-theme/src/elements/ui/TextField.js

- remove border colour change for 'success' and 'warning' states on `TextField` & `TextArea`
fixes #303 
Visually, manually

remove success & warning borders on validation

---

.gitlab-ci.yml
app/components/submission/WithCurrentSubmission.js

`isAutoSave` wasn't being passed through resulting in emails being sent when the form was auto saved rather than only when the "Next" button was clicked.

fix: add missing params to update mutation

---

app/components/dashboard/DashboardPage.js
config/default.js
config/development.js

Use the new `morganLogFormat` option in `pubsweet-server` to improve the log output.
- Log graphql operation name
- Don't log user agent string
- Only log remote IP and time in test/production
Old:
```
info: ::1 - - [11/Jul/2018:11:14:41 +0000] "POST /graphql HTTP/1.1" 200 133 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
info: ::1 - - [11/Jul/2018:11:14:41 +0000] "POST /graphql HTTP/1.1" 200 385 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
```
New (development):
```
info: POST /graphql 200 CurrentUser 133 361.909 ms
info: POST /graphql 200 DashboardManuscripts 385 11.297 ms
```
New …

feat: improve request logging

---

.gitlab-ci.yml

Addresses #331 
Uses [pubsweet/kubernetes](https://gitlab.coko.foundation/pubsweet/infra/blob/master/kubernetes/Dockerfile) and [Gitlab CI](https://gitlab.com/elifesciences/elife-xpub/pipeline_schedules) to scale down the Kubernetes cluster at 8pm, and scale up the cluster at 8am on weekdays. 
After the operation, a rolling update will be performed to balance deployments across the cluster, to balance out resource usage, CPU being the main concern. This takes about an hour.
The scheduled jobs can be [run manually](https://gitlab.com/elifesciences/elife-xpub/pipeline_schedules), which has been done.

Scaling down the cluster out of hours

---

server/jest-setup.js

The server-side tests have been failing sporadically on our local machines. This was because all the tests were all using the same default database causing them to be polluted by each other's setup. They were meant to be using a dynamically created database to avoid this.
This allows the tests to be run in parallel on multi-core machines, but they would pass on CI because of the build runners having a single core.

fix: using dynamic test databases rather than a default

---

package.json

There are cases where you would want to stop and cleanly remove the postgres service locally on your machine. This script removes the service as well as it's volume, so the next time it's started, you get a clean container which gets set up from scratch.

chore: added script to stop database and remove volumes

---

app/components/global/Centerer.js
app/components/global/Layout.js
app/components/pages/SubmissionWizard/steps/Author/AuthorDetails.md
app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerModal.js
app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerModal.md
app/components/pages/SubmissionWizard/steps/Editors/index.md
app/components/pages/SubmissionWizard/steps/Files/FileUploads.md
app/components/pages/SubmissionWizard/steps/Submission/index.md
app/components/ui/molecules/ModalOverlay.js

Creates an instance of a `ModalOverlay` with appropriate layout and Add/Cancel buttons. The people picker search and selection interface will be slotted in here when complete.
Closes #346 
Closes #356 
Visually in styleguide.

feat: people picker modal container with margins and buttons

---

styleguide.config.js

Right now the `README.md` from material icons is picked by react styleguidist and this is not intended behavior.

fix(styleguide): remove material icons by themselves from the styleguide

---

.eslintrc
server/submission/resolvers.js

The default config for https://eslint.org/docs/rules/prefer-destructuring leads to convoluted code. This change in config turns the rule off for all but the simplest case and has already been applied to `pubsweet/pubsweet`.

refactor: relax eslint destructuring rule

---

server/submission/resolvers.js

Typo in refactor, thankfully caught by tests, sadly still allowed to be merged as CI hadn't yet reported the failure.

fix: bad refactor of array destructuring

---

app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerModal.js
app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerModal.md
app/components/ui/atoms/PersonPod.js
app/components/ui/atoms/SelectedItem.js
app/components/ui/molecules/PeoplePicker.js
app/components/ui/molecules/PeoplePicker.md
app/components/ui/molecules/PeoplePicker.test.js

Implement the `PeoplePicker` component which ties together the selected item tags, the selection hint message, the person pod search results and the button bar.
Closes #354 
Closes #355 
~~Uses a dummy person pod implementation pending #227.~~
Visually with styleguide and functionally with Jest.

feat: people picker selection functionality

---

app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerModal.md
app/components/ui/atoms/PersonPod.js
app/components/ui/atoms/PersonPod.md
app/components/ui/atoms/PersonPod.test.js
app/components/ui/molecules/PeoplePicker.js
app/components/ui/molecules/PeoplePicker.md
app/components/ui/molecules/PeoplePicker.test.js

1. Refactor, as per comment in #227:
- `PersonPod` -> `PersonPodContainer`
- `ChosenPersonPod` -> `PersonPod`
- `ChoosePersonPod` -> `PersonPod.SelectButton`
I don't think this is necessarily ideal, as it suggests that `SelectButton` is a sub-component of `PersonPod`, which is not really accurate. Unfortunately, styleguidist does not seem to allow you to export 2 components from the same file? :confused: Suggestions welcome!
2. Specify prop types
3. Add tests
4. Tiny fix - keywords are now a small paragraph rather than regular
#227 
Icon clicking & keyword clicking has been tested for `PersonPod`.
Disabling the icon hasn't been tested, since this functionality is coming in a different PR - #390

refactor person pod, add prop types & tests

---

app/components/pages/Dashboard/Dashboard.md
app/components/pages/Manuscript/Manuscript.md
app/components/pages/SubmissionWizard/steps/Files/FileUploads.md
app/components/ui/atoms/Textarea.md

Fix some broken component examples in styleguide.
Also remove some text about required props since this is generated automatically by Styleguidist using `PropTypes`.

fix: some broken component examples in styleguide

---

app/components/ui/atoms/PersonPod.js
app/components/ui/atoms/icons/Plus.js
app/components/ui/atoms/icons/RubbishBin.js
app/components/ui/atoms/icons/SelectedTick.js

- use regular HTML `button` element instead of pubsweet's button atom, since we don't need the regular hover behaviour for pubsweet buttons
- change/add padding to RHS of icon, so that spacing between icon and RHS of pod conform to styleguide
- change icon colours on hover using `fill`
Note:
The colour change has to happen when the user hovers over the button (not just the icon itself i.e. the SVG), so we need to change the CSS of the child from within the parent. But the parent (button) doesn't know which child (i.e. which icon) it has inside it. Hence the somewhat ugly `svg > path` & `svg > g > circle`
I considered changing the code structure altogether, to have `StyledPlusButton`, `StyledRubbishButton`, `StyledTickButton`, in order to apply different hover styles based on which icon …

change colour of person pod icons on hover

---

.gitlab-ci.yml

Complete the work that @fampinheiro has done migrating the Kubernetes cluster to its own AWS account.
If the pipeline passes then it's working.

ci: switch CD domain name to use new Kubernetes cluster

---

app/components/pages/SubmissionWizard/steps/Editors/EditorsContent.js
app/components/ui/atoms/PersonPod.js

- fix: set people picker fields as touched after editing
- fix: set button type to prevent premature submission
Closes #434 
Manually.

fix: editor step field validation display

---

server/submission/elife-api.js

Fixes both server and client errors in the case the endpoint returns an empty body
locally

Handle when the people endpoint of the elife-api returns an empty body

---

app/components/pages/SubmissionWizard/operations.js
app/components/pages/SubmissionWizard/steps/Editors/EditorsContent.js
server/submission/definitions.js
server/submission/elife.graphqls
server/submission/resolvers.js
server/submission/resolvers.test.js

- Keep the same data shape on the client and in the input types
- Store suggested and opposed editors, author and suggested reviewers as teams
- Leave opposed reviewers because the change in design is likely to mean the opposed reason is no longer associated with the team members
Closes #436 
- ~~reviewers left alone due to ongoing work in #336~~
- submitter left until after #423 due to the complexity in crafting appropriate SQL statements
Existing tests updated.

refactor: use teams to persist author and suggested editors

---

server/xpub/index.js
server/xpub/schema/migrations/1533672892-initial.sql
server/xpub/schema/migrations/1533830042-elife.sql
server/xpub/schema/xpub.graphqls

First stab at a SQL schema corresponding to the GraphQL schema already in use.
There's also [a MR open in PubSweet](https://gitlab.coko.foundation/xpub/shared-data-model/merge_requests/8) for this.
Closes #423 
Manually in Postgres and through pubsweet migrations.

feat: SQL schema for shared data model

---

config/custom-environment-variables.js

- These were accidentally added under "client" instead of "server"

fix: move custom environment variables into correct location

---

app/components/pages/SubmissionWizard/index.js
app/components/pages/SubmissionWizard/steps/Submission/index.js

- Makes minor amendments to the labelling of text input fields on the Submission screen.
- Updates title of Step 1 of the wizard. This is because we are dropping the corresponding author delegation feature from the first release. The application now only records the details of one person, who fulfills both the roles of submitter and corresponding author.

Update co-submission input labelling and author step title

---

package.json
yarn.lock

Upgrades `pubsweet-client` to allow websocket connections to be established over https.
#507 
CI

feat: upgraded pubsweet-client to 4.1.2

---

app/components/pages/SubmissionWizard/steps/Files/index.js
app/components/ui/molecules/FileUpload.js
app/components/ui/molecules/FileUpload.test.js
config/development.js
package.json
server/xpub/entities/manuscript/resolvers.js
server/xpub/entities/manuscript/resolvers.test.js
server/xpub/entities/manuscript/typeDefs.graphqls
server/xpub/package.json
yarn.lock

#518 reverted the upload progress due to WebSockets not working over https on `pubsweet-client`. [Version 4.1.3](https://gitlab.coko.foundation/pubsweet/pubsweet/blob/master/packages/client/CHANGELOG.md) of `pubsweet-client` has fixed the problem.
#518 #507 
CI, manually deployed to demo environment and verified features.

Reintroducing subscription resolver and upload progress

---

app/components/ui/atoms/PersonPod.js

- removes prop-types warning about `institution` in `PersonPod` (by no longer making this prop required)
- in the situation where institution comes back null, display a placeholder space in the Person Pod
fixes #404 "Keep space for missing items in person pod"
fixes #403 "Handle editors with no institution"
Visually & no more warning when running tests

leave space in person pod if institution is null

---

server/xpub/schema/migrations/1533830042-elife.sql

I have already added `submitterSignature` & `disclosureConsent` to the `elife.graphqls` schema in PR #496 
See [these lines of code](https://github.com/elifesciences/elife-xpub/blob/develop/server/xpub/schema/elife.graphqls#L5-L6) already in `develop`
Add these values to the db migration file
Fixes #490 
N/A

add data disclosure info to db migration file

---

app/components/pages/SubmissionWizard/index.js
test/pageObjects/file-uploads.js
test/pageObjects/metadata.js
test/pageObjects/suggestions.js

WIP - This is only the first step in issue #523 
- change URLs to reflect wizard step names
- `BASEURL/dashboard` -> `BASEURL/` (both were being used for the same page in our app - changed to just the home root)
- (wizard step 1 aka "author" is still just `BASEURL/submit/`)
- `BASEURL/submit/upload` -> `BASEURL/submit/files`
- `BASEURL/submit/metadata` -> `BASEURL/submit/submission`
- `BASEURL/submit/suggestions` -> `BASEURL/submit/editors`
- (step 5 remains `BASEURL/submit/disclosure`)
#523 
No tests for the routing yet

WIP: bring urls in line with the names of our wizard steps

---

app/components/pages/SubmissionWizard/steps/Disclosure/index.js
package.json
yarn.lock

- Uses `date-fns` to display the current date on the data disclosure page, based on the user's timezone
fixes #519 
Automated tests: N/A - using an external library
Visually:
- The date is **3rd sept** when the timezone of my OS is set to London, UK
- The date is **4th sept** when the timezone of my OS is set to Canberra, Australia:

feat(DisclosurePage): display current date on disclosure page

---

app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerModal.md

Documents the current behaviour of the search box within the context of the People Picker

Add documentation of people picker search

---

app/components/ui/molecules/CrossIconButton.js
app/components/ui/molecules/CrossIconButton.md
app/components/ui/molecules/SearchBox.js
client/elife-theme/src/index.js

- create button component using cross icon
- add to searchbox component, in between the input field (react-autosuggest) & the search button
- add CSS styling to make it look like the cross icon sits inside of the input field - make the border of both elements the same, then remove the right-hand border of the input field & the left-hand border of the clear button
- when the button is clicked, the input field is cleared & the person pods are updated
fixes #540 
Pending the addition of the appropriate test files

add cross icon that clears search box & refreshes pods

---

app.js
newrelic.js
package.json
yarn.lock

Enable NewRelic monitoring in the app (when started through `app.js`). Requires a valid license key to be configured.
Part of #579 
Manually.

feat: install new relic monitoring

---

config/authsome.js
server/meca/index.js
server/meca/index.test.js
server/xpub/entities/manuscript/data-access.js
server/xpub/entities/manuscript/data-access.test.data.js
server/xpub/entities/manuscript/data-access.test.js
server/xpub/entities/manuscript/helpers/empty.js
server/xpub/entities/manuscript/resolvers.js
server/xpub/entities/manuscript/resolvers.test.js
server/xpub/entities/user/resolvers.test.js

- Update authsome mode to deny all requests. Authsome is only used by built in PubSweet endpoints and resolvers so this has the effect of disabling these. 
- Update data access functions to only fetch manuscript for current user ID. This means a user can only gain access to a manuscript if they also created it.
Suggestions of alternate approaches welcome.
Closes #580 
Jest integration tests for resolvers and data access tests updated.

fix: prevent users from accessing or modifying others manuscripts

---

app/components/ui/molecules/FileUpload.js

Add new line about files larger than 10MB to follow new designs:
#560 
Visually

add message about large files to FileUpload component

---

server/xpub/entities/manuscript/index.js
server/xpub/entities/manuscript/resolvers.js
server/xpub/entities/manuscript/resolvers.test.js

Fixes #591 
Dashboard functionality is deliberately not covered by tests because it's throw away code. But obviously that was a silly decision.

fix: pass user in manuscript delete mutation

---

app/components/pages/Dashboard/Dashboard.js
app/components/pages/Manuscript/Manuscript.js
app/components/pages/Manuscript/Manuscript.md
app/components/pages/Manuscript/index.js
app/components/pages/SubmissionWizard/steps/Files/FilesPage.js
app/components/pages/SubmissionWizard/steps/Files/index.js
app/components/ui/molecules/FileUpload.js
app/components/ui/molecules/FileUpload.test.js
app/routes.js
test/pageObjects/files.js
test/submission.e2e.js

Planning to do a little refactoring so I'm not using `<br />` before taking this off WIP status
- Remove Manuscript page
- Remove preview link from FileUpload component
- Remove the clickable link from the dashboard
- Minor refactor to replace `Instruction` with `Paragraph` component in `FileUpload`
Note: design for "success" now looks like this
fixes #560 
Removed tests that refer to this page & use the link

remove Manuscript preview page from our app

---

app/components/pages/SubmissionWizard/operations.js
server/xpub/entities/manuscript/data-access.js
server/xpub/entities/manuscript/helpers/empty.js
server/xpub/entities/manuscript/index.js
server/xpub/entities/manuscript/resolvers.js
server/xpub/entities/manuscript/resolvers.test.data.js
server/xpub/entities/manuscript/resolvers.test.js
server/xpub/entities/manuscript/typeDefs.graphqls
server/xpub/schema/migrations/1536842027-opposed-reviewers.sql

This fixes the issue I was seeing on iOS Safari preventing submission of the form. 
- Add opposed_reviewers_reason to SQL schema.
- Add test to ensure all manuscript properties are persisted.
- Remove opposedReviewers property now that these are handled through teams.

fix: persist opposed reviewers reason

---

app/components/ui/molecules/SearchBox.js

- make top-left & bottom-left corners of search box square, but top-right and bottom-right = border-radius variable
- fix width of search & clear buttons to 48px
fixes #614 
Visually

tweak searchbox button styling

---

server/xpub/entities/manuscript/resolvers.js

This is not needed anymore since the issue was solved in https://github.com/elifesciences/elife-xpub-formula/pull/33.

revert(graphql-subscriptions): remove logging for upload progress

---

server/xpub/entities/manuscript/index.js
server/xpub/entities/manuscript/resolvers.js
server/xpub/entities/manuscript/resolvers.test.js
server/xpub/entities/manuscript/typeDefs.graphqls
test/submission.e2e.js

- Rename `QA` status to `PENDING_MECA_EXPORT`.
- Add a `MECA_EXPORT_SUCCEEDED` status.
- Lookup statuses in a dictionary.
Note since the export happens asynchronously there are a couple of potential race conditions. If these do materialise, they can be fixed by asserting that the status is *either* pending or succeeded.

refactor: rename manuscript statuses

---

docker-compose.yml

See https://github.com/elifesciences/builder/pull/393 for AWS support reasons: going back to `10.4` from the current default `10.5`.
No idea where to change what is used in building PRs to this repository.

Specify postgres:10.4 for local usage

---

server/xpub/entities/manuscript/resolvers.test.js
test/submission.e2e.js

Implemented to stop the need to retry tests. See #659

Disable the test as a temporary workround

---

config/production.js

Disables SFTP uploads in demo and production, until we've fully configured it by addressing #621 
Created change in demo manually and tested.

Disable SFTP in demo and production

---

client/elife-theme/src/elements/ui/Button.js

As per discussions with @chugginselifesciences  and @davidcmoulton  ... the font weight in a button should be 500

Change font weight of button to be consistent with eLife

---

config/ci.js
config/demo.js
config/prod.js
config/production.js

Dependant on the following: 
- https://github.com/elifesciences/elife-xpub-deployment/pull/12
- https://github.com/elifesciences/elife-xpub-formula/pull/36
- https://github.com/elifesciences/builder-configuration/pull/3
Production has ORCID secrets set to allow it to work with the sandbox disabled. Without this, production fails.
- Verified `config` locally to ensure `NODE_CONFIG_ENV` can be used to load environment specific config files within `/config`

Disable ORCID sandbox in production

---

server/meca/index.test.js
server/meca/test/mock-sftp-server.js
server/meca/upload/index.js

Uploads to SFTP site as a different name, then rename when done - to prevent eJP from prematurely processing
* NOTE *  this is branched from `520-manuscript-s3` #668 ... so please merge after this.
#642 
Locally with mock sftp server

MECA rename

---

config/default.js
config/test-e2e.js
config/test.js
server/meca/file-generators/manuscript.js
server/meca/index.js
server/meca/index.test.data.json
server/meca/index.test.js
server/meca/test/mock-sftp-server.js
server/meca/upload/client/s3.js
server/meca/upload/index.js
server/xpub/entities/file/index.js
server/xpub/entities/manuscript/resolvers.js
server/xpub/entities/manuscript/resolvers.test.js
server/xpub/test/mock-s3-server.js
test/helpers/setup.js

- Save manuscripts file contents in S3
- Restructure config to share AWS credentials between packages.
- Refactor MECA package to not access the database. This avoids circular dependency between xpub-server and xpub-meca-export packages.
Closes #520 
Integration tests with mock S3 server, end to end tests updated.

feat: store manuscripts in S3

---

server/xpub/entities/manuscript/resolvers.js

No longer show a successful upload when the manuscript fails to upload to S3. This would then fail the MECA ZIP file export.
Locally

Showing user an error when uploading a manuscripts to S3 fails

---

app/components/pages/Login/index.js
app/components/pages/Login/index.test.js
server/xpub/entities/user/resolvers.js
server/xpub/entities/user/resolvers.test.js
server/xpub/entities/user/routes.js
server/xpub/entities/user/typeDefs.graphqls

When a token is passed in the URL, trigger a GraphQL mutation to exchange this for a longer lived token, then save this to local storage. If the token exchange fails (the only likely cause I can think for this is a network issue)then redirect the user to the login page.
Closes #678 
Unit tests.

feat: exchange journal token for longer lived xpub token

---

app/index-production.html

Closes #684 
This happened because now we are actually running a production build, it's using the production `index.html` but the meta viewport tag had only been added to the development index.

fix: mobile view in production

---

package.json
webpack/babel-includes.js
webpack/webpack.production.config.js
webpack/webpack.test.config.js
yarn.lock

Does the minimum to get the app to load in IE11.
- Add `babel-polyfill`
- Ensure config directory is transpiled
End to end tests now almost pass. Some layout issues to sort on the people picker.
Related #612 
Using a time machine.

fix: add babel-polyfill for ie11 support

---

Dockerfile

Creates a folder for logs within the container
#693 
Locally I can build and run the container successfully logging to `/var/log/xpub`

Create a local folder for logs in the container.

---

server/xpub/entities/file/index.js
server/xpub/entities/manuscript/resolvers.js

We've had several bugs related to the way streams are handled in the upload resolver. I've spent most of today trying to make sense of it but in the end I've opted to read the whole file into a string and pass that around instead. It's not as efficient but it's simpler and less buggy. Optimisation can come later.
I'll try and write up the issues tomorrow.

fix: don't use streams in upload resolver

---

config/components.json
server/meca/file-generators/article.helpers.js
server/meca/file-generators/article.js
server/meca/file-generators/article.test.data.json
server/meca/file-generators/article.test.js
server/meca/index.test.js
server/meca/migrations/1538487310-ejp-name.sql
server/meca/nameSplitter.js
server/meca/nameSplitter.test.js

- Set up a database table to hold list of known authors with spaces in their forenames
- Use this list of exceptions when creating the MECA export to split the reviewer name into its parts
Closes #643

feat: split reviewer name using rule with list of known exceptions

---

server/xpub/entities/file/index.js
server/xpub/entities/identity/index.js
server/xpub/entities/manuscript/index.js
server/xpub/entities/manuscript/index.test.js
server/xpub/entities/team/index.js
server/xpub/entities/user/index.js
server/xpub/entities/user/index.test.js

Fix a bug in the entity access logic that silently ignored saving an entity which had an ID but didn't exist in the database.
Jest integration tests.

fix: prevent updating an entity which doesn't exist

---

docs/testing/README.md

docs: some notes on debugging CI test failures locally

---

server/xpub/entities/manuscript/resolvers.js
server/xpub/entities/manuscript/resolvers.test.js

Fixes #714 by deleting the file entity from the database if saving the content of the file fails.

fix: clean up manuscript file after failed upload

---

package.json
server/dupes/index.js
server/dupes/package.json
yarn.lock

Having duplicates of certain dependencies can cause hard-to-debug problems. The previous solution we had for checking duplicates only looked in `node_modules` and wasn't aware of yarn workspaces. This quick fix looks at the `yarn.lock` file and errors if any of the named packages are present in more than one version.
Manually.

feat: duplicate package checker that works with workspaces

---

config/default.js
config/staging.js
server/xpub/entities/user/helpers/elife-api.js

Closes #727 
Locally by copying the JWT and resigning it.

feat: make API gateway url configurable

---

app/components/pages/Dashboard/Dashboard.js
app/components/pages/Dashboard/index.js
app/components/pages/SubmissionWizard/WithCurrentSubmission.js
app/components/pages/SubmissionWizard/index.js
app/components/pages/SubmissionWizard/operations.js
app/routes.js
server/xpub/entities/manuscript/resolvers.js
server/xpub/entities/manuscript/resolvers.test.js
server/xpub/entities/manuscript/typeDefs.graphqls
test/pageObjects/author.js
test/pageObjects/disclosure.js
test/pageObjects/editors.js
test/pageObjects/files.js
test/pageObjects/submission.js
test/submission.e2e.js

- Make the "Submit a manuscript" button always create a new submission
- Update the wizard to include the manuscript UUID in the URL
- Remove `currentSubmission` query and resolver
- Link manuscripts on the dashboard to the in progress submission
Closes #730 and addresses most of #732.
Needs more end to end tests but delaying until Dashboard is available.

feat: allow concurrent submissions

---

Dockerfile

For https://github.com/elifesciences/elife-xpub/issues/619, it seems it should be included at the top level:
```
elife@staging--xpub:/srv/elife-xpub$ docker-compose exec app /bin/bash
root@2f2e41886e72:~# ls -la
total 768
drwxr-xr-x    1 root root   4096 Oct  9 11:20 .
drwxr-xr-x    1 root root   4096 Jan  8  2018 ..
drwxr-xr-x    2 root root   4096 Oct  9 11:14 .aws
-rw-rw-rw-    1 root root     44 Oct  9 09:21 .babelrc
-rw-------    1 root root      6 Oct  9 11:20 .bash_history
-rw-rw-rw-    1 root root     29 Oct  9 09:21 .eslintignore
-rw-rw-rw-    1 root root    660 Oct  9 09:21 .eslintrc
drwxr-xr-x    3 root root   4096 Oct  9 09:23 .node-gyp
drwxr-xr-x    3 root root   4096 Jan  8  2018 .npm
-rw-rw-rw-    1 root root     69 Oct  9 09:21 .prettierrc
-rw-rw-rw-    1 root root     26 …
```

Copy New Relic configuration into container image

---

docs/developing/README.md
docs/developing/quick-start.md

- Made `docs/development/quick-start.md` easier to find
- Added a section on starting dependencies locally
- Using `yarn` rather than `npm run`, since we're already using yarn to install dependencies

Update development docs

---

app/components/global/AppBar.js
app/components/pages/Login/index.js
app/components/pages/Login/index.test.js
app/routes.js
config/default.js
server/xpub/entities/user/routes.js

Closes #735 
- Read JWT on client and respond to `new-session` claim.
- If `false` this means the user was already logged in to Journal so show interstitial with 'Continue' button
- If `true` user has already been shown xPub log in screen so redirect straight to dashboard
- Update the login screen text and layout (took a few liberties with the second paragraph of text).

feat: add login interstitial

---

app/components/pages/SubmissionWizard/steps/Submission/SubjectAreaDropdown.js
config/default.js
server/meca/__snapshots__/export.test.js.snap
server/meca/export.test.js
server/meca/file-generators/__snapshots__/article.test.js.snap
server/meca/file-generators/article.helpers.js
server/meca/file-generators/article.js
server/meca/file-generators/article.test.js

Closes #771 
- I made the assumption that the major subject area text eJP matches against is the text label as displayed in the "Major Subject Area(s)" page of the submission form.
- Moved definition of subject areas into config to enable mapping from our internal ID to the external label.
- Swapped the ad-hoc XML testing for a snapshot test as this provides a nicer diff when things change

fix: meca article.xml tweaks

---

config/staging.js

Allows users to get past login on Staging while #787 is addressed. Production already has the login mock enabled, which allows us to use it for testing.

fix: enable login mock on staging

---

package.json

We're not using the test coverage as a statistic, and it only serves to make the test output more verbose.

Disable test coverage

---

app/components/pages/SubmissionWizard/AutoSave.js
app/components/pages/SubmissionWizard/AutoSave.test.js
app/components/pages/SubmissionWizard/WizardStep.js
server/xpub/entities/manuscript/resolvers.js
server/xpub/entities/manuscript/resolvers.test.js

- Throw an error when calling `updateManuscript` or `submitManuscript` on a manuscript with a status other than `INITIAL`
- Disable auto saving of the form while is it submitting to prevent double submit on componentWillUnmount
Closes #800

fix: prevent updating submitted manuscript

---

config/non-serializable/mock-logger.js
server/meca/services/upload.js
test/submission.e2e.js

- Use Node `assert` instead of TestCafe `.expect` in order to avoid strange problems when asserting in a loop

ci: fix auto retry assertion mechanism

---

app/components/global/AppBar/index.js
app/components/global/ErrorBoundary.js
app/routes.js

- Also add error boundaries around app bar and main content. This should avoid a white page though it can result in odd output like <img width="586" alt="screen shot 2018-10-18 at 15 36 32" src="https://user-images.githubusercontent.com/115310/47162340-a740f600-d2eb-11e8-853f-4b81e425a9ce.png">

fix: display app bar even if currentUser query fails

---

config/prod.js

Disables the mock and uses real endpoints for login and API calls in production.
This change doesn't enable EJP integration/SFTP upload

Enabling production login and API

---

app/components/ui/molecules/StaffCard.js
app/components/ui/molecules/StaffCard.md

Create a Staff Card component for use on the static content pages.
- photo
- name (required)
- job title (required)
- phone number (required)
This should mimic styling found on https://submit.elifesciences.org/html/contact.html#
Adds a StaffCard component that can be nested in a `styled-grid` box and takes the profile info as props.
closes #824
Visually within styleguide

824 - Create StaffCard Component

---

app/components/ui/atoms/CrossIconButton.md
app/components/ui/atoms/StickyFooter.md
app/components/ui/molecules/PeoplePicker.md
app/components/ui/molecules/Tabs.md
client/texture/TextureEditor.md

- Fix the styleguide examples to clean up the console errors.
- Add a button to show/hide the sticky footer example otherwise it's always there.

fix: clean up styleguide errors

---

app/components/global/layout/TwoColumnLayout.js

Use `React.Children.map` to allow layout to handle single, non-array child.

fix: allow TwoColumnLayout to handle single child

---

app/components/ui/molecules/DashboardList.js
app/components/ui/molecules/DashboardListItem.js

Currently all submissions on dashboard have a link to the submission wizard, including those that are awaiting decision. Opening these submissions in the wizard throws a graphql error as mutations are blocked on submission data with status "MECA_IMPORT_SUCCEEDED"
Removes the Link wrapper around DashboardListItem's that are in the manuscript status of "WAITING_FOR_DECISION"
closes #857 
locally

857 - Remove link from completed dashboard items

---

app/components/pages/SubmissionWizard/WizardStep.js

Each step of the form is conceptually a separate form with its own validation state and submitted state. However due to the structure of the components, when navigating from one step to the next, React re-uses the previous component instance leading to issues where all form fields are already touched and validation messages are shown too soon.
In order to avoid this, we give the `Formik` component in `WizardStep` a `key` prop which is unique for each step. This tell React that they are not the same element and a new instance should be created. Previously we used `FormComponent.name` as the unique key but this name is only available in development builds meaning that in production the key was undefined.
Closes #842

fix: give each form step a unique key even in production

---

styleguide.config.js

Styleguide was showing all components within the *Other* section.
[This was due to a bug in styleguidist which was fixed on version 8.0.2](https://github.com/styleguidist/react-styleguidist/commit/a7a6cf410060244f5157b80d3be7d4f12ab10e09#diff-37941dbdd4961cdef0779884f6621f61)
This change fixes the problem until styleguidist gets upgraded on pubsweet.
The problem can be reproduced using the following snippet: 
```
const glob = require('glob');
const path = require('path');
const rootDir = '/Users/hem/Projects/elife/elife-xpub'
const components = 'app/**/*.js'
const ignore = [
'app/components/{global,pages,ui}/**/*.js'
]
const componentFiles = glob.sync(
path.resolve(rootDir, components),
{ ignore }
)
console.log(componentFiles)
```
Changing `ignore` to …

fix: fixed Other section within styleguide

---

app/components/global/AppBar/AppBar.js
app/components/global/AppBar/index.js
app/components/global/layout/Layout.js

Previously AppBar's Desktop menu was hard coded NavLinks and a seperate set of config was passed to burger menu for the mobile view. This left the possibility of adding to one in the future and forgetting about the other.
Allows config for the AppBar menu to be passed in through the Layout Component as `userMenuItems` for signed in users and `defaultMenuITems` for all users. This one entry point for config is then used to generate both mobile and desktop view menus
closes#888
locally

888 - Consolidate AppBar menu config to be passed in one place

---

styleguide.config.js

The molecules section was actually showing atoms rather than molecules.

fix: showing molecules on styleguide

---

app/components/ui/atoms/ManuscriptStatus.js
app/components/ui/atoms/ManuscriptStatus.md
app/components/ui/molecules/DashboardList.js
app/components/ui/molecules/DashboardList.md
app/components/ui/molecules/DashboardListItem.js
app/components/ui/molecules/DashboardListItem.md
server/xpub-server/entities/manuscript/resolvers.js
test/submission.browser.js

- Change all instances of 'waiting for decision' to 'submitted'
- Add all different states of `DashboardListItem` to styleguidist:
- different titles
- each of 3 manuscript statuses
- different dates, to show the various outputs (today, yesterday, x days ago)
- Changed `title` to required prop in DashboardListItem, since it's parent (DashboardList) is actually the one responsible for deciding what title gets sent to it (i.e. decides whether it says 'untiltled' or not)
fixes #886 
Existing test altered

886 manuscript status updates

---

yarn.lock

Removes the dependencies from `yarn.lock` that were removed as part of #883.
Ran yarn locally and verified there were no changes locally

fix: removed unused dependencies from yarn.lock

---

app/components/ui/molecules/DashboardList.js
app/components/ui/molecules/DashboardListItem.js
app/components/ui/molecules/DashboardListItem.md

- Currently the data passed to `DashboardListItem` is pre processed (ie: if no title on manuscript object the Dashboard passes '(Untitled)' down. The `DashboardListItem` should have control over how it shows the manuscript data.
- Fix bug with non-link dashboard items still changing to primaryColor on hover.
Refactors `DashboardListItem` to take the whole manuscript object as a prop and format things like date and title for display.
closes #898
closes #905
visually

898 & 905 - refactor DashboardListItem to take the whole manuscript

---

.env.ci
Jenkinsfile
docker-compose.ci.yml
scripts/test-ci.sql
scripts/test.sql

The first step of https://github.com/elifesciences/elife-xpub/issues/675
Ports over the following Gitlab CI jobs, using a `docker-compose` configuration:
- `build`
- `lint`
- `test`
- `test:browser`
- `test:dependencies`
These provide feedback in the form of commit status checks. Execution time seems slightly better (~20-30 seconds less per job) than on Gitlab CI, probably because of lower overhead when running on a single node but possibly also dedicated hardware.
There is more in Gitlab CI, but some of these could be reasonably removed from there once they are stable on this side, reducing the execution time.

Build image on eLife's infrastructure, run tests

---

app/components/ui/molecules/BurgerMenu.js
app/components/ui/molecules/BurgerMenu.test.js

'Burger' menu on the journal site has all NavLinks as `textColor` irrespective of active state.
Makes all `BurgerMenu` NavLinks `textColor`
closes #906 
visually

906 - Change mobile menu to colorText

---

app/components/pages/StaticPages/SideNav.js
app/components/pages/StaticPages/SideNav.md
app/components/pages/StaticPages/index.js

- Design uses a 12 column grid on sketch
- Developers use fractions/percentages of viewport width (see [`grid-styled` docs](https://github.com/rebassjs/grid#responsive-styles))
To recap on our use of grid-styled...
We have an array of 4 breakpoints [in our theme](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/index.js#L61): `[480, 768, 1000, 1272]`.
So whenever we add `width={[1stNum, 2ndNum, 3rdNum, 4thNum, 5thNum]}` to one of our `Flex` or `Box` components, it means that those numbers are applied to the component's width as follows:
- `width=1stNum` until viewport width reaches 480px
- `2ndNum` from 480px (inclusive) until 768px
- `3rdNum` from 768px (inclusive) until 1000px
- `4thNum` from 1000px (inclusive) until 1272px
- `5thNum` from 1272px …

style(StaticPages): fix responsive grid as applied to static page layout

---

app/components/global/AppBar/ProfileMenu.js
app/components/pages/Dashboard/index.js
app/components/pages/Login/index.js
app/components/pages/StaticPages/AuthorGuide/EditorialProcess.js
app/components/pages/StaticPages/AuthorGuide/Fees.js
app/components/pages/StaticPages/AuthorGuide/Full.js
app/components/pages/StaticPages/AuthorGuide/Initial.js
app/components/pages/StaticPages/AuthorGuide/JournalMetrics.js
app/components/pages/StaticPages/AuthorGuide/JournalPolicies.js
app/components/pages/StaticPages/AuthorGuide/Post.js
app/components/pages/StaticPages/AuthorGuide/Revised.js
app/components/pages/StaticPages/AuthorGuide/Types.js
app/components/pages/StaticPages/ReviewerGuide/ReviewProcess.js
app/components/pages/StaticPages/ReviewerGuide/ReviewingPolicies.js
app/components/pages/StaticPages/ReviewerGuide/WritingTheReview.js
app/components/pages/SubmissionWizard/steps/Disclosure/index.js
app/components/pages/ThankYou/ThankYou.js
app/components/ui/atoms/ExternalLink.md
app/components/ui/atoms/NativeLink.js
app/components/ui/atoms/NativeLink.md

At the moment we use 2 (or 3) different types of links in our application:
- `ExternalLink` - our own component: an anchor tag with eLife styling applied
- `Link` from pubsweet - which uses react-router's `Link` under the hood & applies styling)
(Note: elsewhere we also import `Link` directly from react-router, in situations where it's not styled normally i.e. non-blue links in ProfileMenu, DashboardList, etc.)
Until now, we had never linked to a heading within the same page (via an id).
- Fixes broken links in `EditorialProcess` & `Fees` components by changing `Link` (react-router) to `ExternalLink` (regular anchor tag)
- Renames the `ExternalLink` component to `NativeLink`, to better describe all use cases
- Updates ExternalLInk/Native Link styleguidist description accordingly
Fixes …

Fix internal page anchor links

---

app/components/pages/StaticPages/index.js
app/components/pages/StaticPages/index.test.js
app/components/ui/atoms/NavigationDropdown.js
app/components/ui/atoms/NavigationDropdown.md

- Adds the NavigationDropdown to StaticPages
- Removes internal state from NavigationDropdown (again :yum:) & pass info directly from StaticPages into react-select component
fixes #820 
Change `makeWrapper`, to update existing tests. It now:
- wraps everything in `ThemeProvider`
- passes down history from `MemoryRouter` into `Route` component, which then renders `StaticPage`

Static pages mobile nav

---

app/components/ui/molecules/DashboardListItem.js
app/components/ui/molecules/DashboardListItem.test.js

Improves the display of dates on the dashboard item.
Closes 957
Locally

Improve dashboarditem dates and add tests

---

.gitlab-ci.yml

- Deleting production and staging jobs from Gitlab, since we're using elife environments, and the existing jobs deployed to kubrnetes instead
- Moved styleguide deployment, and docker image push to a new stage called `deploy`

Gitlab CI cleanup

---

app/components/ui/atoms/NavigationDropdown.js

Background colour of dropdown was grey before becoming active. It should be `colorBackground` like the dropdown options list at all times.
Sets the dropdown's in-active background to `colorBackground`.
closes #965
visually

965 - default dropdown background color is now colorBackground

---

app/components/global/AppBar/ProfileMenu.js
app/components/ui/molecules/DashboardListItem.js
app/components/ui/molecules/StaffCard.js
client/elife-theme/src/elements/ui/Action.js
client/elife-theme/src/elements/ui/Button.js
client/elife-theme/src/elements/ui/Heading.js

Noto Sans SemiBold + non-Chrome browsers do not play well :cry: 
- override default font family of `Button` component in pubsweet, to now use `Noto Sans SemiBold`
- over-override font family `Action` component (that sometimes uses Button under the hood), so this is back to just `Noto Sans`
- add `font-weight: 400` everywhere that we use our `fontHeading` theme variable (aka `Noto Sans SemiBold` font family)
fixes #915 
relates #687 
N/A - style change

Fix semibold issue

---

client/elife-theme/src/global.js

IE doesn't support the `woff2` file format that we are using to load the `NotoSans` and `NotoSerif` fonts within the app. This is causing the app to fallback to a system font in IE. 
Adds fallback styling import of a `woff` file for the `Noto` fonts when the users browser is unable to load the `woff2` file type.
closes#990
visually within IE11

990 - Add woff fallback for fonts

---

client/elife-theme/src/global.js

The last PR for adding `woff` files used the wrong `woff` asset file for Serif font fallback
Corrects this mistake.

Fix wrong woff file being used for Serif fallback

---

Jenkinsfile
scripts/helm_deploy.sh
scripts/helm_url.sh

Experimental deploy through an Helm chart on the eLife `kubernetes--demo` cluster. Relies on the `master` version of the [chart](https://github.com/elifesciences/elife-xpub-formula/tree/master/helm/elife-xpub), parameterizing the image tag to use.
Very limited scope:
- pushes the image built by Jenkins at `elifesciences/elife-xpub` in the same Docker Hub organization as the other projects
- allows to but see the login page but has no database yet, hence clicking around will give a `ECONNREFUSED` error
- provide a URL to reach that in the `continuous-integration/jenkins/deploy-for-review` commit status check

Push image and deploy the Helm chart - review scheduled for Friday

---

Jenkinsfile

From https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1009/3/pipeline/35 we see:
```
wait-for-it.sh: waiting 15 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 8 seconds
```
While `test:browser` correctly waited in this way the slow startup of `postgres`, `test` didn't and failed like this:
```
connect ECONNREFUSED 172.19.0.2:5432
```
Better to wait for `postgres` startup before initiating any testing job. This slow startup was probably caused by a new Jenkins agent having to download the image from scratch.

Wait for postgres before any test job

---

test/helpers/replay-setup.js

Stops the Authorization header being recorded in replay files, so we don't push secrets to the repository within our mocks.
Related to #1017 
Added an authorization header to requests, and made sure new replay files didn't contain the header

Disable authorization header on replay

---

app/components/ui/molecules/FileUpload.js

Primarily for Selenium end-to-end testing to understand when the file has finished uploading, but only the `completed` value is necessary there.
https://github.com/elifesciences/elife-xpub/blob/a8e5bc83de9021c72500a3167a6ad5d0d84e497f/app/components/ui/molecules/FileUpload.test.js#L29 could rely on these to check the various states instead of on the text; or use them in addition to the text.
https://github.com/elifesciences/elife-xpub/blob/develop/test/submission.browser.js#L85 has a bare sleep that could also rely on a waiting condition like this instead, to improve stability.

Add selectors for file upload result

---

Jenkinsfile

`latest` as the most recent version of `develop` that passed tests. This is equivalent to what Gitlab CI does for the older image `xpub/xpub-elife`.
We do this only on the mainline and not on pull requests.

Publish elifesciences/elife-xpub:latest

---

scripts/helm_deploy.sh

Recently https://github.com/elifesciences/elife-xpub-formula/pull/57 introduced a `stable/postgresql` chart as a dependency, to make the review environments work properly providing a database. The script needs to be expanded to resolve this dependency and download it before installation.

Install Helm charts as dependencies

---

app/components/ui/atoms/ManuscriptStatus.js
app/components/ui/molecules/DashboardListItem.js

Uses tablet portrait breakpoint for dashboard list items, to apply either mobile or desktop designs.
You can see the breakpoints [here](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/index.js#L61) and [here](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/global/layout/media.js#L4-L9)
Closes #1000 
Review environment

Using tablet breakpoint on dashboard

---

app/components/pages/SubmissionWizard/steps/Files/index.js
app/components/pages/SubmissionWizard/steps/Files/index.test.js
app/components/pages/SubmissionWizard/steps/Files/utils.js
app/jest.config.js
server/xpub-server/entities/manuscript/resolvers/index.js
server/xpub-server/entities/manuscript/resolvers/removeUploadedManuscript.js
server/xpub-server/entities/manuscript/resolvers/removeUploadedManuscript.test.js
server/xpub-server/entities/manuscript/resolvers/uploadManuscript.js
server/xpub-server/entities/manuscript/resolvers/uploadManuscript.test.js
server/xpub-server/entities/manuscript/typeDefs.graphqls

When there is a client side validation error on the manuscript upload field, the Submission should delete its current Manuscript file.
- Refactors the way Manuscript files are uploaded so that there is only ever one of type `MANUSCRIPT_SOURCE` in the manuscript.files field. 
- Extends tests to check any previous manuscript file gets replaced.
- Adds a removeManuscriptUpload mutation to remove any existing manuscript file
- Adds test for removing an upload
- calls the removeManuscriptUpload mutation when a client side upload validation error occurs 
close #1034 
Unit tests

1034 remove manuscript on error

---

Jenkinsfile
docker-compose.ci.yml
docker-compose.override.yml
docker-compose.yml

This implements a common eLife docker-compose pattern:
- local usage targets automatically `docker-compose.yml` and `docker-compose.override.yml` files, which are merged together when you run `docker-compose anycommand`.
- CI uses `docker-compose -f docker-compose.yml -f docker-compose.ci.yml anycommand`, and these two files are merged together instead.
`docker-compose.yml` remains only for the common settings.
With this separation, we can use the [`dockerComposeBuild`](https://github.com/elifesciences/elife-jenkins-workflow-libs/blob/master/vars/dockerComposeBuild.groovy) custom Jenkins step, which enforces verbosity and is now logging exceptions so that we can classify errors and provide retries on e.g. Docker Hub timing out.

Use common dockerComposeBuild step

---

config/end2end.js
config/staging.js
docs/deploying/infrastructure.md

`elifesciences.org` does not go directly to the `journal`'s load balancer, but is a Fastly CDN instead that wraps it.
Therefore `end2end` and `staging` should also go through the CDN e.g. redirecting to it rather than to the non-CDN URL.
This is especially important for testing environments to be able to use the behavior defined in https://github.com/elifesciences/builder/pull/430

Use journal's CDN consistently

---

server/xpub-model/entities/user/helpers/elife-api.js
server/xpub-model/entities/user/helpers/elife-api.test.js

Logs any errors that occur when calling the eLife API.
#1090 #1065

Logging on error when calling eLife API

---

README.md

Very small change, just to illustrate Jenkins review environments that get generated on pull requests.

Use Jenkins canonical hostname

---

app/components/pages/SubmissionWizard/steps/Files/ManuscriptUpload.js

display the name of the uploading/uploaded file
closes: #988 
it's a cosmetic change, on the dropzone file name should be display while uploading/uploaded a file

display the name of the uploading/uploaded file

---

app/components/pages/Dashboard/EjpLink.js
app/components/pages/SubmissionWizard/operations.js
app/components/pages/SubmissionWizard/steps/Disclosure/index.js
app/components/pages/SubmissionWizard/steps/Editors/EditorsPage.md
app/components/pages/SubmissionWizard/steps/Editors/EditorsPage.test.js
app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerControl.js
app/components/pages/SubmissionWizard/steps/Editors/PeoplePickerModal.md
app/components/pages/SubmissionWizard/steps/Editors/index.js
app/components/pages/SubmissionWizard/steps/Files/ManuscriptUpload.js
app/components/pages/ThankYou/ThankYou.js
app/components/ui/atoms/Paragraph.js
app/components/ui/atoms/PersonInfo.js
app/components/ui/atoms/PersonInfo.md
app/components/ui/atoms/PersonPod.js
app/components/ui/atoms/PersonPod.md
app/components/ui/atoms/PersonPod.test.js
app/components/ui/atoms/SmallParagraph.js
app/components/ui/molecules/ModalDialog.js
app/components/ui/molecules/ModalDialog.md
app/components/ui/molecules/PeoplePicker.js
app/components/ui/molecules/PeoplePicker.md
app/components/ui/molecules/PeoplePicker.test.js
server/xpub-model/entities/user/helpers/elife-api.js
server/xpub-server/entities/manuscript/resolvers/index.js
server/xpub-server/entities/manuscript/typeDefs.graphqls
server/xpub-server/entities/user/resolvers.test.js

- add new `PersonInfo` component - text that goes inside new modal dialog
- refactor existing `Paragraph` & `SmallParagraph` components to allow `secondary` prop for text colour (make consistent across the rest of the existing codebase)
- separate subjectAreas into focuses & expertises when making the API call to eLife's `/people` endpoint, so that we can separate these in the modal view
- refactor PersonPod to make it easier to add to
- render modal inside PersonPod, make PersonPod stateful to keep track of whether the modal is open
- hook up to PeoplePickerModal & PeoplePickerControl
To do:
- tests
- change `ModalDialog` in order to satisfy this product req:
> Clicking outside of the lightbox should close the modal
Could raise in a new ticket for the to dos?
Closes #635 
Adjusted …

add person info modal to people picker

---

.env.ci
config/ci.js
config/custom-environment-variables.js
docker-compose.ci.yml
docker-compose.override.yml
docker-compose.yml
package.json

For https://github.com/elifesciences/elife-xpub/issues/1064
Useful to get `app` to talk to the `fakes3` container rather than a real S3 bucket. We would run `fakes3` in CI, too, despite not using it by default for now.
Shouldn't affect tests as they have a `test` environment that is separate from `ci` anyway. `ci` would be used to run pull request review environments.
Probably `ci` is used also for `elife-xpub--ci` usage in the `develop` branch, but right now the environment variable should be empty so it should be irrelevant.

Allow S3_ENDPOINT environment variable

---

app/components/ui/molecules/DashboardListItem.js
app/components/ui/molecules/ModalDialog.js
client/elife-theme/src/elements/ui/Button.js
test/delete.submision.browser.js

once a manuscript is being deleted, we need the user confirmed first if this can be deleted
creates a dialogue to ask the user
closes: #1107 
create a submission go back to the dashboard, so the manuscript is fully submitted, and then press the trash button a dialogue should appear

1107 confirmation dialog manuscript delete

---

server/xpub-model/entities/user/helpers/elife-api.js
server/xpub-model/entities/user/helpers/elife-api.test.js
server/xpub-model/entities/user/helpers/elife-api.test.person.js

End 2 End test is failing as the test data being returned from the person api does not contain `research` data. This is not a required field according to the api schema so the xpub `elife-api` should be able to handle uesrs with the minimum required data.
Casts any undefined `research` value within person data to an empty object to prevent the `elife-api` from throwing an error.
Extends `elife-api.test.js` to run a test against the minimum required details that may be returned from the person api.

Fix failing e2e test

---

Jenkinsfile

At the moment https://alfred.elifesciences.org/job/dependencies/job/dependencies-elife-xpub-deployment-update-xpub/ updates the Docker image tag of `elife-xpub` to use on `elife-xpub--*` environments (EC2 instances deploying it with `docker-compose`).
That pipeline is triggered by a Docker Hub hook that follows Gitlab's push of the image built by Gitlab CI (`xpub/xpub-elife`).
This change triggers that pipeline right after the successful completion of this pipeline instead. It also passes a `commit` parameter so that we don't have to read labels anymore from the Docker image, relying on this value instead.
This additional trigger is unnecessary at the moment, but it opens the way for `elife-xpub-deployment` to:
- start using the `elifesciences/elife-xpub` Docker image built by Jenkins in …

Trigger elife-xpub-deployment update directly

---

config/ci.js

For https://github.com/elifesciences/elife-xpub/issues/1064#issuecomment-442754324
Exploring with the build why was [this commit](https://github.com/elifesciences/elife-xpub/pull/1117/commits/b07650cb6fc0a315218b44c9c47be64a7210f4cf) necessary. I am trying to:
- use `test` and `docker-compose.ci.yml` for all automated testing
- use `ci` and Kubernetes, Helm for review environments
`elife-xpub--ci` is dead so won't use any environment.

Force ci to use fakes3 on its fixed port

---

config/default.js
server/xpub-server/entities/manuscript/resolvers/uploadManuscript.js

- Increased Sciencebeam timeout
- Used a time-based prediction method for upload progress - see #839 for the maths
Closes #839 
Tested locally - already have the end2end and browser tests

Change upload progress and sciencebeam timeout

---

Dockerfile
package.json
yarn.lock

We currently accept any version of yarn greater than 1.2.
1.10 introduced a new field in the `yarn.lock` file, which [gets stripped out when using earlier versions](https://github.com/yarnpkg/yarn/issues/6440)
We generally use the latest version of yarn locally, so this change will throw an error if an earlier version of yarn is used.

Upgrade yarn to 1.10.1

---

Dockerfile
Dockerfile-base

The image for `elife-xpub` gets [built from `xpub/xpub`](https://github.com/elifesciences/elife-xpub/blob/develop/Dockerfile#L1) which in turn is currently built from [yld/xpub-deployment-config-postgres](https://gitlab.coko.foundation/yld/xpub-deployment-config-postgres/blob/master/images/xpub-base/Dockerfile)
This change relocated the base Dockerfile to the elife-xpub repository.
Unblocks #1199 
Manually built and pushed the image, and tested CI for develop and PRs

Added base Dockerfile

---

config/formula.js

Spawned from https://github.com/elifesciences/elife-xpub-formula/pull/64
We know `ci` by now is only used inside Kubernetes review environments and will be renamed to [`review`](https://github.com/elifesciences/elife-xpub/issues/1153).
This makes an alternative copy `formula` that uses all similar empty/local defaults, but doesn't talk to `fakes3` as this is not there in the formula.
The formula is used for production-like environments:
- `end2end`
- `staging`
- `prod`
Those are working with their own environment configuration, but we need a similar environment to run the tests of the formula itself (e.g. creating a server from scratch whenever a change is made.)

Fork ci into a `formula` environment

---

config/staging.js

Also from https://github.com/elifesciences/elife-xpub/issues/890
[By default](https://github.com/elifesciences/elife-xpub/blob/develop/config/default.js#L86) environments use `fake-mailer.js` rather than `mailer.js`, which is only used in `prod`. To send real emails from `staging` we need to do the same.
Also the [test configuration](https://github.com/elifesciences/elife-xpub/blob/develop/config/test.js#L52-L61) looks wrong as the [documentation](https://gitlab.coko.foundation/pubsweet/pubsweet/tree/master/packages/components/SendEmail-server/) states this object should be configured just with the `path` field.

Configure staging to use mailer rather than fake-mailer

---

styleguide/components/StyleGuideRenderer.js
styleguide/components/Wrapper.js

The styleguide broke due to the recent Pubsweet upgrade introduce in #1237 
This fix uses the new method to add global styles to the styleguide, and removes the old method.

Fixing styleguide

---

server/meca/file-generators/article.helpers.js

Allows eJP to import the correct article type.
Closes 1262
Tested locally for a features article type and got:
```      <article-id pub-id-type="manuscript">987a81b3-be8c-4f54-9b0f-de22ad399743</article-id>
<article-categories>
<subj-group subj-group-type="article_type">
<subject>24</subject>```

1262 Update/fix article types

---

server/xpub-server/entities/manuscript/resolvers/uploadManuscript.js
server/xpub-server/entities/manuscript/resolvers/uploadManuscript.test.js
server/xpub-server/entities/manuscript/resolvers/uploadSupportingFile.js
server/xpub-server/entities/manuscript/resolvers/uploadSupportingFile.test.js

Stores the mimetype on the file object in the database and uses it in the MECA package build.
Closes #1164 
Tested locally ....

1164 mimetype store

---

app/components/pages/SubmissionWizard/steps/Editors/EditorsPage.js
app/components/pages/SubmissionWizard/steps/Editors/EditorsPage.md
app/components/pages/SubmissionWizard/steps/Editors/EditorsPage.test.js
app/components/pages/SubmissionWizard/steps/Editors/SuggestedReviewersValidator.js
server/xpub-model/entities/manuscript/index.js

- Removes the requirement to have three suggested reviewers making all optional (but maintaining the limit of six)
- Reduces the initial number of suggested reviewer inputs displayed from three to one
- Extends the EditorPage unit test to test the functionality of adding new inputs when the user fills in blank suggestedReviewer rows and remove trailing empty detail rows.
- Corrects some typos in the props passed to the People picker modal components.
closes #1010
closes #1024
Please indicate the need for this change to be tested. If not please justify, if so then at what levels.

1010 reviewer suggestion

---

app/components/pages/SubmissionWizard/steps/Editors/schema.js

https://github.com/elifesciences/elife-xpub/issues/1140
Changes the max number of `senior editors` to be excluded.
Closes #1140 
Please indicate the need for this change to be tested. If not please justify, if so then at what levels.

1140 Fix/ exclude only 1 senior editor

---

app/components/pages/SubmissionWizard/steps/Files/SupportingUpload.js

When uploading enough files to bring the total supporting files to 10, the validation message advising that 10 is the maximum should be displayed while the uploads are in progress and not after the success of the action.
closes #1196
Please indicate the need for this change to be tested. If not please justify, if so then at what levels.

1196 - Supporting files max upload validation message
